spring.application.name=setcelium
spring.datasource.url=jdbc:postgresql://localhost:5432/setcelium
spring.datasource.username=lukejames
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
anthropic.api.key=${ANTHROPIC_API_KEY}
spring.servlet.multipart.max-file-size=150MB
spring.servlet.multipart.max-request-size=150MB